name: "seqscreen_window_fasta"
description: Split FASTA records into overlapping windows for SeqScreen analysis
keywords:
  - seqscreen
  - fasta
  - windows
tools:
  - "seqscreen":
      description: "SeqScreen pathogen detection and sequence-of-concern reporting"
      homepage: "https://gitlab.com/treangenlab/seqscreen"
      documentation: "https://gitlab.com/treangenlab/seqscreen"
      licence: "['GPL-3.0-or-later']"
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - fasta:
      type: file
      description: Validated input FASTA file
output:
  - fasta:
      type: file
      description: Windowed FASTA output
      pattern: "*.windowed.fasta"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@ppreshant"
