name: "UTILS_NFCORE_PIPELINE"
description: Subworkflow with reusable pipeline utility functions
keywords:
  - utility
  - pipeline
  - initialise
  - version
components: []
input:
  - nextflow_cli_args:
      type: list
      description: |
        Nextflow CLI positional arguments
output:
  - success:
      type: boolean
      description: |
        Dummy output to indicate success
authors:
  - "@adamrtalbot"
maintainers:
  - "@adamrtalbot"
  - "@maxulysse"
