---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: rhea
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - networkx>=3.2
  - seaborn
  - flye # TODO: need to use the module and pipe input to rhea
  - minigraph # TODO: need to use the module and pipe input to rhea
  - pip
  - pip:
    - git+https://github.com/treangenlab/rhea.git@python_package_i8
