repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-somatem_logo_light.png
    - docs/images/nf-core-somatem_logo_light.png
    - docs/images/nf-core-somatem_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-somatem_logo_light.png
    - docs/images/nf-core-somatem_logo_light.png
    - docs/images/nf-core-somatem_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - CHANGELOG.md
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - assets/multiqc_config.yml
    - nextflow_schema.json
  readme:
    - nextflow_badge
    - nextflow_badge
    - nfcore_template_badge
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: Somatem
  description: "A long-read metagenomics pipeline with support for longitudinal analysis "
  author: Prashant Kalvapalle, Austin Marshall
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github
    - github_badges
    - changelog
    - license
    - multiqc
    - fastqc
    - nf_schema
    - seqera_platform
    - gitpod
    - codespaces
    - vscode
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
