---
config:
  theme: redux
---
flowchart TD

 subgraph Preprocess
     direction LR
     trimming["Quality/adapter trimming<br>(chopper | fitlong)"]  
     dehost["Remove host contamination<br>(hostile)"]
     QC["QC<br>(NanoPlot)"]
     trimming --> dehost --> QC
 end

 subgraph Laptop_Mode["Laptop mode<br>(read based)"]
     tax16s["Taxonomic profiling<br>(Emu)"]
     readanalysis["Read based analysis"]
     taxonomic["Taxonomic profiling<br>(Lemur + MAGnet | Centrifuge | Sylph)"]
     classification["Read classification<br>(SeqScreen, Centrifuge)"]
     pathogen["Pathogen identification<br>(MAGnet, SeqScreen)"]
     functional["Functional annotation<br>(SeqScreen, EggNOG-mapper, HUMAnN)"]
    readanalysis --> taxonomic 
    readanalysis --> classification 
    readanalysis --> pathogen 
    readanalysis --> functional
 end

 subgraph Workstation_Mode["Workstation mode<br>(assembly-based)"]
     assembly["Assembly"]
     denovo(["De novo<br>(Flye | Canu | AutoCycler)"]) --> binning
     refguided(["Reference-guided<br>(MetaCompass)"]) --> annotation
     binning(["Binning"]) --> annotation
     annotation["Genome annotation<br>(pangenomics, ARGs, etc)"]
     assembly --> denovo & refguided 
 end

 QC --"metagenomic"--> assembly
 QC --"16S amplicon"--> tax16s
 QC --"metagenomic"--> readanalysis
 

%% Notes:
%% add length to trimming node (length filtering)
%% add depth sampling node