---
config:
  theme: redux
---
flowchart TD

 subgraph Preprocess
     direction LR
     trimming["Quality/adapter trimming<br>(chopper | fitlong)"]  
     dehost["Remove host contamination<br>(hostile)"]
     QC["QC<br>(NanoPlot)"]
     trimming --> dehost --> QC
 end

 subgraph Laptop_Mode["Laptop mode<br>(read based)"]
     tax16s["Taxonomic profiling<br>(Emu)"]
     taxonomic["Taxonomic profiling<br>(Lemur + MAGnet | Centrifuge | Sylph)"]
     
     readanalysis(["Other read based analysis"])
     classification["Read classification<br>(SeqScreen, Centrifuge)"]
     pathogen["Pathogen identification<br>(MAGnet, SeqScreen)"]
     functional["Functional annotation<br>(SeqScreen, EggNOG-mapper, HUMAnN)"]
    
    readanalysis --> classification & pathogen & functional
 end

 subgraph Workstation_Mode["Workstation mode<br>(assembly-based)"]
     assembly(["Assembly"])
     denovo["De novo<br>(Flye | Canu | AutoCycler)"] --> binning
     refguided["Reference-guided<br>(MetaCompass)"]
     binning["Binning"]
     annotation["Genome annotation"]
     
     othergenomic(["multi-genomic analyses"])
     pangenomics["Pangenomics<br>(tmhg-finder)"]
     genesnp["Structural variation<br> Gene duplication/loss<br>(rhea)"]
     metabolic["Metabolic reconstruction<br>(bakdrive | micom | apollo)"]
     
     assembly --> denovo & refguided 
     refguided & binning --> annotation
     annotation --> othergenomic
     othergenomic --> pangenomics & genesnp & metabolic

 end

 QC --"metagenomic"--> assembly
 QC --"16S amplicon"--> tax16s
 QC --"metagenomic"--> taxonomic & readanalysis
 

%% Notes:
%% add length to trimming node (length filtering)
%% add depth sampling node