flowchart TD
 subgraph laptop["Laptop mode"]
        asm["Assembly<br>(meta)"]
        metacomp["MetaCompass"]
        flye["Flye"]
        autocycler["AutoCycler"]
  end
 subgraph cluster["Cluster mode (MetaCompass, Flye, AutoCycler)"]
        asm["Assembly<br>(meta)"]
        metacomp["MetaCompass"]
        flye["Flye"]
        autocycler["AutoCycler"]
  end